### ISSUE TITLE
How can we build this toolkit?

### ISSUE THREAD

**Issue by geyao1995** [QuanEstimation/QuanEstimation#193]
Thanks for your excellent work! However, we can not find `quanestimation` in PyPI. So if we need to build the toolkit on our own, can you give the instructions step by step?

**Comment by HM-Yuuu** [comment]
Welcome to the QuanEstimation community! Feel free to submit issues and pull requests.

We are still working hard uploading our package to the PyPI and making our docs online. And we are also waiting for our [QuanEstimation.jl registration](https://github.com/JuliaRegistries/General/pull/61399#issuecomment-1142241816) to be auto-merged, which will be much more convenient for our users to setup their julia environment.  
So, it's highly recommended to wait until all these works are finished, and follow our documentations to have a better using experience.

Nevertheless, if you still want to manually install the toolkit, you can
1. `git clone` this repo to local and `cd QuanEstimaiton`,
2. `pip install .` or `python setup.py install` to install the python package,
3. [download julia](https://julialang.org/downloads/) and install. Or simply via `pip install jill` and `jill install`,
4. set up  julia environment by adding the dependences. Currently this step is somewhat cumbersome,
    1. check [Julia's docs](https://docs.julialang.org/en/v1/stdlib/Pkg/) if you  are not familiar with julia's package management,
    2. add the deps [here](https://github.com/QuanEstimation/QuanEstimation.jl/blob/e1b3b5ab5ac23c01eacd56de5440fcdcf36358d4/Project.toml#L6) to your julia environment **via julia's REPL** manually
    3. and then run python from command line to set up pyjulia, see [pyJulia’s documentation](https://pyjulia.readthedocs.io/en/stable/)
    ```python
        import julia
        julia.install()
    ```
5. `import QuanEstimation` to load the package. 
6. then run the examples in `quanestimation/examples/` folder and play around.

P.S. if the julia pacakges in step4 can't be added due to network problems, have a look at [here](https://discourse.juliacn.com/t/topic/2969) or [here](https://mirrors.tuna.tsinghua.edu.cn/help/julia/) for help.

Eager to help if any more discussions
